# Generated by Django 6.0.2 on 2026-07-30 14:06

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(help_text="Only the Video ID from the YouTube URL, e.g. 'dQw4w9WgXcQ'", max_length=20, validators=[django.core.validators.RegexValidator(message='Enter just the video ID: 6–20 letters, digits, hyphen or underscore.', regex='^[A-Za-z0-9_-]{6,20}$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(help_text='Max 25 MB. Allowed: pdf, doc, docx, ppt, pptx, xls, xlsx, csv, txt, rtf, png, jpg, jpeg, webp, gif, zip.', upload_to='resources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'txt', 'rtf', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'zip']), core.models.validate_resource_size]),
        ),
    ]
