# Generated by Django 6.0.2 on 2026-08-09 07:43

import curriculum.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-collection', help_text="Bootstrap Icon class e.g. 'bi-mortarboard'", max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text="Hex colour for this kind's badge, e.g. #6366f1.", max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a 6-digit hex colour, e.g. #6366f1.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='URL segment. Auto-filled from the name.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='class_thumbnails/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('icon', models.CharField(default='bi-mortarboard', help_text='Bootstrap Icon class, used when there is no thumbnail.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from students without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.ForeignKey(blank=True, help_text='Optional grouping, e.g. School or Bootcamp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.coursekind')),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('youtube_video_id', models.CharField(help_text="Only the Video ID from the YouTube URL, e.g. 'dQw4w9WgXcQ'", max_length=20, validators=[django.core.validators.RegexValidator(message='Enter just the video ID: 6–20 letters, digits, hyphen or underscore.', regex='^[A-Za-z0-9_-]{6,20}$')])),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Max 25 MB. Allowed: pdf, doc, docx, ppt, pptx, xls, xlsx, csv, txt, rtf, png, jpg, jpeg, webp, gif, zip.', upload_to='resources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'csv', 'txt', 'rtf', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'zip']), curriculum.models.validate_resource_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='curriculum.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL segment. Auto-filled from the name.')),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='bi-book', help_text="Bootstrap Icon class e.g. 'bi-calculator'", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from students without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the class.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.class', verbose_name='class')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('klass', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='curriculum.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'slug')},
        ),
    ]
