# Generated by Django 6.0.2 on 2026-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(help_text='URL segment. Auto-filled from the name.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coursekind',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(help_text='URL segment. Auto-filled from the name.', max_length=100),
        ),
    ]
